"""
fitness.py — Curvature + coupling divergence fitness evaluation.

The honest audit (PR #2770) found that curvature (Pancharatnam phase) is
the one metric that held up. That becomes the primary fitness signal.

Fitness = w1*curvature + w2*coupling_divergence + w3*loss_improvement

Where:
  - curvature: Pancharatnam phase of embedding trajectory (proven metric)
  - coupling_divergence: does M diverge more on external vs self-generated text?
  - loss_improvement: is prediction loss decreasing across breaths?

Weights: w1=0.5, w2=0.3, w3=0.2 — curvature dominates because it's the
only signal we trust.

No external dependencies beyond numpy.
"""

import math
import numpy as np


# ── Curvature measurement ────────────────────────────────────────────────
# Adapted from spark/creature.py measure_curvature()


def compute_curvature(text, embed_fn):
    """Pancharatnam phase of embedding trajectory.

    This is the measurement that survived the honest audit. It tracks
    directional change in semantic space — texts that reframe within
    a tight conceptual space accumulate more phase than texts that
    hop between distant topics.

    Args:
        text: string to measure
        embed_fn: callable(list[str]) -> np.ndarray of shape (n, dim)

    Returns:
        (angle: float, curvature_per_segment: float)
    """
    words = text.split()
    chunk_size = max(5, len(words) // 8)
    chunks = []
    for i in range(0, len(words), chunk_size):
        c = ' '.join(words[i:i + chunk_size])
        if c.strip():
            chunks.append(c)

    if len(chunks) < 3:
        return 0.0, 0.0

    vecs = embed_fn(chunks)

    # Treat real vector as complex: pairs of (re, im)
    phase_re, phase_im = 1.0, 0.0

    for i in range(len(vecs)):
        j = (i + 1) % len(vecs)
        v1 = vecs[i].reshape(-1, 2)
        v2 = vecs[j].reshape(-1, 2)
        re = float(np.sum(v1[:, 0] * v2[:, 0] + v1[:, 1] * v2[:, 1]))
        im = float(np.sum(v1[:, 1] * v2[:, 0] - v1[:, 0] * v2[:, 1]))
        mag = math.sqrt(re ** 2 + im ** 2)
        if mag < 1e-12:
            continue
        re /= mag
        im /= mag
        new_re = phase_re * re - phase_im * im
        new_im = phase_re * im + phase_im * re
        phase_re, phase_im = new_re, new_im

    angle = math.atan2(phase_im, phase_re)
    curv = abs(angle) / max(len(chunks) - 1, 1)
    return angle, curv


# ── Embedding fallback ───────────────────────────────────────────────────

def default_embed_fn(texts):
    """Deterministic embedding fallback when no sentence model is available.

    Uses hash-seeded random vectors. Not semantically meaningful, but
    deterministic and sufficient for testing the pipeline.
    """
    vecs = []
    for t in texts:
        rng = np.random.RandomState(hash(t) % 2 ** 31)
        v = rng.randn(384).astype(np.float32)
        v /= np.linalg.norm(v) + 1e-12
        vecs.append(v)
    return np.array(vecs)


# ── Coupling divergence ─────────────────────────────────────────────────

def compute_coupling_divergence(external_texts, self_texts, embed_fn=None,
                                alpha=0.85):
    """Does the complex memory M diverge more on external vs self-generated text?

    The coupled equation: M' = alpha * M + x * e^(i*theta)
    where x = mean curvature and theta = angle.

    If M grows faster on external text than self-generated text, the
    creature is distinguishing outside from inside. That's the coupling
    signal the theory predicts.

    Args:
        external_texts: list of strings from outside
        self_texts: list of strings generated by the creature
        embed_fn: embedding function (defaults to hash-based fallback)
        alpha: memory decay parameter

    Returns:
        float: |M_external| - |M_self|. Positive means external drives
        more growth, which is what we want.
    """
    if embed_fn is None:
        embed_fn = default_embed_fn

    def run_memory(texts):
        mem_re, mem_im = 0.0, 0.0
        for text in texts:
            angle, curv = compute_curvature(text, embed_fn)
            x = max(curv, 0.01)
            mem_re = alpha * mem_re + x * math.cos(angle)
            mem_im = alpha * mem_im + x * math.sin(angle)
        return math.sqrt(mem_re ** 2 + mem_im ** 2)

    mag_ext = run_memory(external_texts) if external_texts else 0.0
    mag_self = run_memory(self_texts) if self_texts else 0.0

    return mag_ext - mag_self


# ── Loss improvement ─────────────────────────────────────────────────────

def compute_loss_improvement(loss_history):
    """Is prediction loss decreasing across breaths?

    Not just "is it low" — "is it decreasing", showing the model is
    adapting to recent input. This measures memorization rate, not
    generalization. Call it what it is.

    Args:
        loss_history: list of dicts from TaskAgent.loss_history, each
            containing 'losses' (list of per-step loss values)

    Returns:
        float: negative slope means improving (loss going down).
        We return -slope so that positive = good for the fitness sum.
    """
    if len(loss_history) < 2:
        return 0.0

    # Take final loss from each breath's learning session
    final_losses = [
        entry['losses'][-1]
        for entry in loss_history
        if entry.get('losses')
    ]

    if len(final_losses) < 2:
        return 0.0

    # Simple linear regression slope
    n = len(final_losses)
    x_mean = (n - 1) / 2.0
    y_mean = sum(final_losses) / n
    num = sum((i - x_mean) * (final_losses[i] - y_mean) for i in range(n))
    den = sum((i - x_mean) ** 2 for i in range(n))

    if den < 1e-12:
        return 0.0

    slope = num / den
    # Negative slope = loss decreasing = improving. Return -slope so positive = good.
    return -slope


# ── Composite fitness ────────────────────────────────────────────────────

# Weights: curvature is the proven metric, so it dominates.
W_CURVATURE = 0.5
W_DIVERGENCE = 0.3
W_LOSS_IMPROVEMENT = 0.2


def compute_fitness(external_texts, self_texts, loss_history,
                    embed_fn=None, alpha=0.85):
    """Compute composite fitness score.

    fitness = w1*curvature + w2*divergence + w3*loss_improvement

    All components are normalized to roughly [0, 1] range so the weights
    are meaningful.

    Args:
        external_texts: list of external input strings
        self_texts: list of self-generated strings
        loss_history: TaskAgent.loss_history
        embed_fn: embedding function (optional)
        alpha: memory decay for coupling divergence

    Returns:
        dict with:
            - fitness: float (composite score)
            - curvature: float (mean curvature across all texts)
            - divergence: float (coupling divergence)
            - loss_improvement: float
            - breakdown: dict of weighted components
    """
    if embed_fn is None:
        embed_fn = default_embed_fn

    # 1. Curvature: mean across all texts
    all_texts = (external_texts or []) + (self_texts or [])
    curvatures = []
    for text in all_texts:
        if len(text.split()) >= 5:
            _, curv = compute_curvature(text, embed_fn)
            curvatures.append(curv)

    mean_curv = sum(curvatures) / len(curvatures) if curvatures else 0.0
    # Normalize: curvature typically in [0, 0.3], scale to [0, 1]
    norm_curv = min(mean_curv / 0.3, 1.0)

    # 2. Coupling divergence
    divergence = compute_coupling_divergence(
        external_texts, self_texts, embed_fn, alpha)
    # Normalize: divergence can be negative; sigmoid-ish mapping
    norm_div = 1.0 / (1.0 + math.exp(-divergence * 5))

    # 3. Loss improvement
    loss_imp = compute_loss_improvement(loss_history)
    # Normalize: clamp to [-1, 1] range
    norm_loss = max(min(loss_imp, 1.0), -1.0)
    # Shift to [0, 1]
    norm_loss = (norm_loss + 1.0) / 2.0

    fitness = (W_CURVATURE * norm_curv
               + W_DIVERGENCE * norm_div
               + W_LOSS_IMPROVEMENT * norm_loss)

    return {
        'fitness': round(fitness, 6),
        'curvature': round(mean_curv, 6),
        'divergence': round(divergence, 6),
        'loss_improvement': round(loss_imp, 6),
        'breakdown': {
            'curvature_weighted': round(W_CURVATURE * norm_curv, 6),
            'divergence_weighted': round(W_DIVERGENCE * norm_div, 6),
            'loss_improvement_weighted': round(W_LOSS_IMPROVEMENT * norm_loss, 6),
        },
    }


# ── Prediction fitness (FM-coupled) ─────────────────────────────────────

def compute_prediction_fitness(fm_loss, self_loss, curvature,
                               learning_rate):
    """Fitness based on live prediction of FM-generated text.

    This replaces the static curvature-only approach with a live
    prediction-as-fitness signal when the FM is available.

    Args:
        fm_loss: mean prediction loss on FM-generated text (external)
        self_loss: mean prediction loss on previous breath text (self)
        curvature: Pancharatnam phase of loss trajectory
        learning_rate: how fast loss drops during fine-tuning
            (measures adaptation speed)

    Returns:
        float: weighted composite fitness score

    Weights: curvature still dominates at 0.5
    """
    # Normalize curvature: typically in [0, 0.3], scale to [0, 1]
    norm_curv = min(abs(curvature) / 0.3, 1.0)

    # Prediction gap: difference between external and self prediction loss
    # Positive gap means FM text is harder to predict than self text
    # (which is good — it means the creature is distinguishing external)
    gap = fm_loss - self_loss if (fm_loss is not None and
                                  self_loss is not None) else 0.0
    # Sigmoid normalization: map gap to [0, 1]
    norm_gap = 1.0 / (1.0 + math.exp(-gap * 2))

    # Loss level: lower FM loss = better prediction = higher fitness
    # Normalize: typical loss in [2, 8] bits, invert and scale
    norm_loss = max(0.0, min(1.0, 1.0 - (fm_loss - 2.0) / 6.0)) if fm_loss else 0.5

    # Learning rate: faster adaptation = higher fitness
    # Normalize: typical learning rate drop in [0, 1]
    norm_lr = min(max(learning_rate, 0.0), 1.0)

    # Composite: curvature dominates at 0.5
    fitness = (0.5 * norm_curv
               + 0.2 * norm_gap
               + 0.15 * norm_loss
               + 0.15 * norm_lr)

    return round(fitness, 6)


# ── imp@k metric (Section 5.2, D.3) ────────────────────────────────────

def improvement_at_k(initial_fitness, archive, k=50):
    """imp@k: performance gain of best agent within k generations.

    Given an initial agent with fitness score `initial_fitness`,
    and an archive of generated variants, return the improvement
    achieved by the best variant within the first k variants.

    This measures how effectively the meta-agent can produce improved
    variants within a limited budget. It's the key metric for
    evaluating hyperagent quality. (Section 5.2, D.3)

    Args:
        initial_fitness: float, fitness of the seed/initial agent
        archive: list of variant dicts with 'generation' and 'fitness' keys
        k: int, maximum number of generations to consider (default 50)

    Returns:
        float: best_fitness - initial_fitness. Positive means improvement.
    """
    variants_within_k = [v for v in archive if v.get('generation', 0) < k]
    if not variants_within_k:
        return 0.0
    best = max(v.get('fitness', 0.0) for v in variants_within_k)
    return best - initial_fitness
