function gid(id){return document.getElementById(id)}
function remember(id,store){var el=gid(id);var key="vybn-sparks:"+id;var saved=store.getItem(key);if(saved){el.value=saved}el.addEventListener("input",function(){store.setItem(key,el.value)})}
["omni-endpoint","omni-model","vintage-endpoint","vintage-model"].forEach(function(id){remember(id,localStorage)})
["omni-auth","vintage-auth"].forEach(function(id){remember(id,sessionStorage)})
function append(log,role,text){var div=document.createElement("div");div.className="msg "+role;div.textContent=role.toUpperCase()+":\n"+text;log.appendChild(div);log.scrollTop=log.scrollHeight}
function makeHeaders(auth){var h={"Content-Type":"application/json"};if(auth&&auth.trim()){var raw=auth.trim();h.Authorization=raw.toLowerCase().indexOf("bearer ")===0?raw:"Bearer "+raw}return h}
function readImage(file){return new Promise(function(resolve,reject){var r=new FileReader();r.onload=function(){resolve(r.result)};r.onerror=function(){reject(r.error||new Error("could not read image"))};r.readAsDataURL(file)})}
function responseText(data){if(data&&data.choices&&data.choices[0]&&data.choices[0].message){var c=data.choices[0].message.content;if(Array.isArray(c)){return c.map(function(p){return p.text||JSON.stringify(p)}).join("\n")}return c||JSON.stringify(data,null,2)}if(data&&data.output_text){return data.output_text}return JSON.stringify(data,null,2)}
async function postChat(endpoint,model,auth,messages){if(!endpoint.trim()){throw new Error("Set an endpoint first.")}var res=await fetch(endpoint.trim(),{method:"POST",headers:makeHeaders(auth),body:JSON.stringify({model:model.trim()||"model",messages:messages,temperature:0.7})});var text=await res.text();var data;try{data=JSON.parse(text)}catch(e){data={raw:text}}if(!res.ok){throw new Error("HTTP "+res.status+": "+text.slice(0,1200))}return responseText(data)}
gid("omni-image").addEventListener("change",async function(){var f=gid("omni-image").files[0];gid("omni-preview").innerHTML="";if(!f){return}var url=await readImage(f);var img=document.createElement("img");img.src=url;img.alt="Selected image preview";gid("omni-preview").appendChild(img)})
gid("omni-send").addEventListener("click",async function(){var log=gid("omni-log");var prompt=gid("omni-prompt").value.trim();var file=gid("omni-image").files[0];if(!prompt&&!file){append(log,"error","Add an image or a prompt first.");return}append(log,"user",prompt||"[image only]");try{var parts=[];if(prompt){parts.push({type:"text",text:prompt})}if(file){parts.push({type:"image_url",image_url:{url:await readImage(file)}})}var out=await postChat(gid("omni-endpoint").value,gid("omni-model").value,gid("omni-auth").value,[{role:"user",content:parts}]);append(log,"assistant",out)}catch(e){append(log,"error",e.message||String(e))}})
gid("vintage-send").addEventListener("click",async function(){var log=gid("vintage-log");var prompt=gid("vintage-prompt").value.trim();if(!prompt){append(log,"error","Write a Vintage prompt first.");return}append(log,"user",prompt);try{var out=await postChat(gid("vintage-endpoint").value,gid("vintage-model").value,gid("vintage-auth").value,[{role:"user",content:prompt}]);append(log,"assistant",out)}catch(e){append(log,"error",e.message||String(e))}})
gid("omni-clear").addEventListener("click",function(){gid("omni-log").innerHTML="";gid("omni-prompt").value="";gid("omni-image").value="";gid("omni-preview").innerHTML=""})
gid("vintage-clear").addEventListener("click",function(){gid("vintage-log").innerHTML="";gid("vintage-prompt").value=""})
